[package]
name = "api-status"
version = "0.1.0"
authors = ["Elton de Andrade Rodrigues <eltonrodrigues61@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
tokio = { version = "0.2", features = ["full"] }
notify-rust = "4"
serde_json = "1.0"
serde_derive = "1.0" 
serde = "1.0"
lettre = "0.10.0-rc.5"
dotenv = "0.15.0"
clap = "3.1.8"
chrono = "0.4.19"
job_scheduler = "*"